name: 游 Solicitar Novo Projeto
description: Solicitar a cria칞칚o de um novo projeto na organiza칞칚o
title: "[NOVO PROJETO] Solicita칞칚o de cria칞칚o de projeto"
labels: ["novo-projeto", "em-an치lise"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por propor um novo projeto! Por favor, preencha as informa칞칫es abaixo para que possamos avaliar sua solicita칞칚o.

  - type: input
    id: project-name
    attributes:
      label: Nome do Projeto
      description: Digite o nome do novo projeto
      placeholder: ex. Sistema de Gerenciamento de Tarefas
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: Descri칞칚o do Projeto
      description: Forne칞a uma breve descri칞칚o do projeto, seus objetivos e poss칤veis benef칤cios
      placeholder: Este projeto visa criar um sistema de...
    validations:
      required: true

  - type: dropdown
    id: use-github-projects
    attributes:
      label: Usar GitHub Projects?
      description: O projeto utilizar치 o GitHub Projects para gest칚o de tarefas?
      options:
        - Sim
        - N칚o
    validations:
      required: true

  - type: checkboxes
    id: repositories
    attributes:
      label: Reposit칩rios a serem criados
      description: Selecione os reposit칩rios necess치rios para o projeto
      options:
        - label: Back-end
        - label: Front-end
        - label: Mobile (Android e iOS)
        - label: Mobile (Multiplataforma)
        - label: Design (apenas se usar GitHub Projects)
        - label: Monorepo (selecione apenas esta op칞칚o se for um 칰nico reposit칩rio para todo o projeto)
    validations:
      required: true

  - type: input
    id: github-username
    attributes:
      label: Seu Username no GitHub
      description: Digite seu nome de usu치rio no GitHub
      placeholder: ex. octocat
    validations:
      required: true

  - type: input
    id: discord-username
    attributes:
      label: Seu Username no Discord
      description: Digite seu nome de usu치rio no Discord (incluindo o #)
      placeholder: ex. usuario
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Obrigado por preencher todas as informa칞칫es. Sua solicita칞칚o ser치 analisada em breve.